from __future__ import annotations

from .gov_report_parsing import (
    _BLS_EMBARGO_DATETIME_PATTERN,
    _COMMON_EN_DATE_PATTERNS,
    _RELEASE_AT_DATETIME_PATTERN,
)

_JP_SOURCES: dict[str, dict] = {
    "jp_boj_statement": {
        "strategy": "listing_regex",
        "url": "https://www.boj.or.jp/en/mopo/mpmdeci/index.htm",
        "base_url": "https://www.boj.or.jp",
        "archive_link_pattern": r"/en/mopo/mpmdeci/state_\d{4}/index\.htm",
        "link_pattern": r"/en/mopo/mpmdeci/mpr_\d{4}/k\d+[a-z]\.pdf",
        "institution": "Bank of Japan",
        "country": "JP",
        "language": "en",
        "data_category": "monetary_policy",
        "importance": "high",
        "allow_pdf_links": True,
        "content_selectors": ["div#main", "div.releaseMain", "div.mb20", "article", "main"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}/\d{2}/\d{2})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "jp_boj_outlook": {
        "strategy": "listing_regex",
        "url": "https://www.boj.or.jp/en/mopo/outlook/index.htm",
        "base_url": "https://www.boj.or.jp",
        "link_pattern": r"/en/mopo/outlook/gor\d+[ab]\.pdf",
        "institution": "Bank of Japan",
        "country": "JP",
        "language": "en",
        "data_category": "monetary_policy",
        "importance": "high",
        "allow_pdf_links": True,
        "content_selectors": ["div#main", "div.releaseMain", "div.mb20", "article", "main"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}/\d{2}/\d{2})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "jp_boj_minutes": {
        "strategy": "listing_regex",
        "url": "https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm",
        "base_url": "https://www.boj.or.jp",
        "link_pattern": r"/en/mopo/mpmsche_minu/minu_\d{4}/g\d+\.pdf",
        "institution": "Bank of Japan",
        "country": "JP",
        "language": "en",
        "data_category": "monetary_policy",
        "importance": "high",
        "allow_pdf_links": True,
        "asset_title": "Minutes of the Monetary Policy Meetings",
        "asset_release_year_from_meeting_year": True,
        "asset_year_pattern": r"minu_(\d{4})/",
        "content_selectors": ["div#main", "div.releaseMain", "div.mb20", "article", "main"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}/\d{2}/\d{2})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "jp_cao_gdp": {
        "strategy": "listing_regex",
        "url": "https://www.esri.cao.go.jp/en/sna/sokuhou/sokuhou_top.html",
        "base_url": "https://www.esri.cao.go.jp",
        "archive_link_pattern": r"/en/sna/data/sokuhou/files/\d{4}/toukei_\d{4}\.html",
        "link_pattern": r"/en/sna/data/sokuhou/files/\d{4}/qe\d+(?:_2)?/gdemenuea\.html",
        "institution": "Cabinet Office",
        "country": "JP",
        "language": "en",
        "data_category": "gdp",
        "importance": "high",
        "content_selectors": ["div#main", "div.releaseMain", "div.mb20", "article", "main"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}/\d{2}/\d{2})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
}

