from __future__ import annotations

from .gov_report_parsing import (
    _BLS_EMBARGO_DATETIME_PATTERN,
    _COMMON_EN_DATE_PATTERNS,
    _RELEASE_AT_DATETIME_PATTERN,
)

_CN_SOURCES: dict[str, dict] = {
    # -- NBS: listing + Chinese keywords ---------------------------------
    "cn_nbs_cpi": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["居民消费价格", "CPI"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "inflation",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_ppi": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["工业生产者出厂价格", "PPI"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "inflation",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_gdp": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["国内生产总值", "GDP", "国民经济"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "gdp",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_pmi": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["采购经理指数", "PMI"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "manufacturing",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_industrial": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["规模以上工业增加值", "工业增加值"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "industrial_production",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_retail": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["社会消费品零售总额", "消费品零售"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "consumption",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    "cn_nbs_fai": {
        "strategy": "listing_keywords",
        "url": "https://www.stats.gov.cn/sj/zxfb/",
        "base_url": "https://www.stats.gov.cn/sj/zxfb",
        "keywords": ["固定资产投资", "投资"],
        "institution": "国家统计局",
        "country": "CN",
        "language": "zh",
        "data_category": "investment",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.center_xilan", "div.xilan_con", "article"],
        "title_selectors": ["h1", "div.xilan_tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
            r"(\d{4}/\d{2}/\d{2})",
        ],
    },
    # -- PBOC: listing + keywords ----------------------------------------
    "cn_pboc_monetary": {
        "strategy": "listing_keywords",
        "url": "http://www.pbc.gov.cn/diaochatongjisi/116219/116319/index.html",
        "base_url": "http://www.pbc.gov.cn",
        "keywords": ["社会融资规模", "M2", "货币供应量", "金融统计"],
        "institution": "中国人民银行",
        "country": "CN",
        "language": "zh",
        "data_category": "monetary",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.content", "article"],
        "title_selectors": ["h1", "div.tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "cn_pboc_lpr": {
        "strategy": "listing_keywords",
        "url": "http://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125440/index.html",
        "base_url": "http://www.pbc.gov.cn",
        "keywords": ["贷款市场报价利率", "LPR"],
        "institution": "中国人民银行",
        "country": "CN",
        "language": "zh",
        "data_category": "interest_rate",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.content", "article"],
        "title_selectors": ["h1", "div.tit", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- Customs: listing + keywords -------------------------------------
    "cn_customs_trade": {
        "strategy": "listing_keywords",
        "url": "http://www.customs.gov.cn/customs/302249/zfxxgk/2799825/302274/302275/index.html",
        "base_url": "http://www.customs.gov.cn",
        "keywords": ["进出口", "外贸", "贸易"],
        "institution": "海关总署",
        "country": "CN",
        "language": "zh",
        "data_category": "trade",
        "importance": "high",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.easysite-news-text", "article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- MOF: listing + keywords -----------------------------------------
    "cn_mof_fiscal": {
        "strategy": "listing_keywords",
        "url": "https://www.mof.gov.cn/zhengwuxinxi/caizhengshuju/",
        "base_url": "https://www.mof.gov.cn",
        "keywords": ["财政收入", "财政支出", "财政数据", "一般公共预算"],
        "institution": "财政部",
        "country": "CN",
        "language": "zh",
        "data_category": "fiscal_policy",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.article-content", "div.content", "article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "cn_mof_bonds": {
        "strategy": "listing_keywords",
        "url": "https://gks.mof.gov.cn/ztztz/guozaiguanli/",
        "base_url": "https://gks.mof.gov.cn/ztztz/guozaiguanli",
        "keywords": ["国债", "地方政府债", "债券", "发行"],
        "institution": "财政部",
        "country": "CN",
        "language": "zh",
        "data_category": "bond_issuance",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.article-content", "div.content", "article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- SAFE: listing + keywords ----------------------------------------
    "cn_safe_fx": {
        "strategy": "listing_keywords",
        "url": "https://www.safe.gov.cn/safe/whcb/index.html",
        "base_url": "https://www.safe.gov.cn/safe/whcb",
        "keywords": ["外汇储备", "储备规模"],
        "institution": "国家外汇管理局",
        "country": "CN",
        "language": "zh",
        "data_category": "fx_reserves",
        "importance": "medium",
        "encoding": "utf-8",
        "content_selectors": ["div.TRS_Editor", "div#zoom", "div.content", "article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\d{4})年(\d{1,2})月(\d{1,2})日",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- Caixin / S&P Global: listing + keywords -------------------------
    "cn_caixin_pmi": {
        "strategy": "listing_keywords",
        "url": "https://www.pmi.spglobal.com/Public/Home/PressRelease",
        "base_url": "https://www.pmi.spglobal.com",
        "keywords": ["caixin"],
        "extra_keywords": ["pmi", "china"],
        "institution": "Caixin/S&P Global",
        "country": "CN",
        "language": "en",
        "data_category": "manufacturing",
        "importance": "high",
        "content_selectors": [".press-release-body", "article", ".content-area", "#content"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
}

