from __future__ import annotations

from .gov_report_parsing import (
    _BLS_EMBARGO_DATETIME_PATTERN,
    _COMMON_EN_DATE_PATTERNS,
    _RELEASE_AT_DATETIME_PATTERN,
)

_US_SOURCES: dict[str, dict] = {
    # -- BLS: fixed URLs -------------------------------------------------
    "us_bls_cpi": {
        "strategy": "fixed_url",
        "url": "https://www.bls.gov/news.release/cpi.htm",
        "institution": "BLS",
        "country": "US",
        "language": "en",
        "data_category": "inflation",
        "importance": "high",
        "default_timezone": "America/New_York",
        "content_selectors": ["#news-release", ".news-release-intro", "#bodytext", "div.body-content"],
        "title_selectors": ["#news-release h2", "#news-release h3", "h1", "title"],
        "datetime_patterns": [
            _BLS_EMBARGO_DATETIME_PATTERN,
        ],
        "date_patterns": [
            r"(?:Released|Issued|Published)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
        ],
    },
    "us_bls_ppi": {
        "strategy": "fixed_url",
        "url": "https://www.bls.gov/news.release/ppi.htm",
        "institution": "BLS",
        "country": "US",
        "language": "en",
        "data_category": "inflation",
        "importance": "high",
        "default_timezone": "America/New_York",
        "content_selectors": ["#news-release", ".news-release-intro", "#bodytext", "div.body-content"],
        "title_selectors": ["#news-release h2", "#news-release h3", "h1", "title"],
        "datetime_patterns": [
            _BLS_EMBARGO_DATETIME_PATTERN,
        ],
        "date_patterns": [
            r"(?:Released|Issued|Published)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
        ],
    },
    "us_bls_nfp": {
        "strategy": "fixed_url",
        "url": "https://www.bls.gov/news.release/empsit.htm",
        "institution": "BLS",
        "country": "US",
        "language": "en",
        "data_category": "employment",
        "importance": "high",
        "default_timezone": "America/New_York",
        "content_selectors": ["#news-release", ".news-release-intro", "#bodytext", "div.body-content"],
        "title_selectors": ["#news-release h2", "#news-release h3", "h1", "title"],
        "datetime_patterns": [
            _BLS_EMBARGO_DATETIME_PATTERN,
        ],
        "date_patterns": [
            r"(?:Released|Issued|Published)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
        ],
    },
    # -- BEA: listing + keywords -----------------------------------------
    "us_bea_gdp": {
        "strategy": "listing_keywords",
        "url": "https://www.bea.gov/news/current-releases",
        "base_url": "https://www.bea.gov",
        "link_must_contain": "/news/",
        "keywords": ["gross domestic product", "gdp"],
        "institution": "BEA",
        "country": "US",
        "language": "en",
        "data_category": "gdp",
        "importance": "high",
        "content_selectors": ["article", ".press-release", ".field--name-body", "#block-bea-content"],
        "title_selectors": ["h1", "article h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_bea_pce": {
        "strategy": "listing_keywords",
        "url": "https://www.bea.gov/news/current-releases",
        "base_url": "https://www.bea.gov",
        "link_must_contain": "/news/",
        "keywords": ["personal consumption", "personal income", "pce"],
        "institution": "BEA",
        "country": "US",
        "language": "en",
        "data_category": "inflation",
        "importance": "high",
        "content_selectors": ["article", ".press-release", ".field--name-body", "#block-bea-content"],
        "title_selectors": ["h1", "article h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_bea_trade": {
        "strategy": "listing_keywords",
        "url": "https://www.bea.gov/news/current-releases",
        "base_url": "https://www.bea.gov",
        "link_must_contain": "/news/",
        "keywords": ["trade", "international trade", "goods and services"],
        "institution": "BEA",
        "country": "US",
        "language": "en",
        "data_category": "trade",
        "importance": "medium",
        "content_selectors": ["article", ".press-release", ".field--name-body", "#block-bea-content"],
        "title_selectors": ["h1", "article h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- Fed: listing + regex --------------------------------------------
    "us_fed_fomc_statement": {
        "strategy": "listing_regex",
        "url": "https://www.federalreserve.gov/newsevents/pressreleases.htm",
        "base_url": "https://www.federalreserve.gov",
        "archive_link_pattern": r"/newsevents/pressreleases/\d{4}-press-fomc\.htm",
        "link_pattern": r"/newsevents/pressreleases/monetary\d{8}a\.htm",
        "institution": "Federal Reserve",
        "country": "US",
        "language": "en",
        "data_category": "monetary_policy",
        "importance": "high",
        "default_timezone": "America/New_York",
        "content_selectors": ["#content", "article", "div.col-xs-12", "#article"],
        "title_selectors": ["title", "h3", "h1", "h2"],
        "datetime_patterns": [
            _RELEASE_AT_DATETIME_PATTERN,
        ],
        "date_patterns": [
            r"(?:Released|Issued|Date)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_fed_fomc_minutes": {
        "strategy": "listing_regex",
        "url": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
        "base_url": "https://www.federalreserve.gov",
        "link_pattern": r"/monetarypolicy/fomcminutes\d{8}\.htm",
        "institution": "Federal Reserve",
        "country": "US",
        "language": "en",
        "data_category": "monetary_policy",
        "importance": "high",
        "content_selectors": ["#content", "article", "div.col-xs-12", "#article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(?:Released|Issued|Date)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_fed_beigebook": {
        "strategy": "listing_regex",
        "url": "https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm",
        "base_url": "https://www.federalreserve.gov",
        "link_pattern": r"/monetarypolicy/beigebook\d{6}\.htm",
        "institution": "Federal Reserve",
        "country": "US",
        "language": "en",
        "data_category": "economic_conditions",
        "importance": "high",
        "content_selectors": ["#content", "article", "div.col-xs-12", "#article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(?:Released|Issued|Date)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_fed_ip": {
        "strategy": "fixed_url",
        "url": "https://www.federalreserve.gov/releases/g17/current/",
        "institution": "Federal Reserve",
        "country": "US",
        "language": "en",
        "data_category": "industrial_production",
        "importance": "medium",
        "content_selectors": ["#content", "article", "div.col-xs-12", "#article"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(?:Released|Issued|Date)[:\s]*(\w+ \d{1,2},?\s*\d{4})",
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- Census: listing + keywords --------------------------------------
    "us_census_retail": {
        "strategy": "listing_keywords",
        "url": "https://www.census.gov/retail/index.html",
        "base_url": "https://www.census.gov",
        "keywords": ["retail", "advance monthly sales"],
        "institution": "Census Bureau",
        "country": "US",
        "language": "en",
        "data_category": "consumption",
        "importance": "medium",
        "content_selectors": [".press-release", "#content", "article", ".uscb-layout-column-2"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_census_housing": {
        "strategy": "listing_keywords",
        "url": "https://www.census.gov/construction/nrc/index.html",
        "base_url": "https://www.census.gov",
        "keywords": ["housing", "new residential", "building permits"],
        "institution": "Census Bureau",
        "country": "US",
        "language": "en",
        "data_category": "housing",
        "importance": "medium",
        "content_selectors": [".press-release", "#content", "article", ".uscb-layout-column-2"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- Treasury: listing + keywords ------------------------------------
    "us_treasury_tic": {
        "strategy": "listing_keywords",
        "url": "https://home.treasury.gov/data/treasury-international-capital-tic-system",
        "base_url": "https://home.treasury.gov",
        "keywords": ["TIC", "treasury international capital", "capital flow"],
        "institution": "Treasury",
        "country": "US",
        "language": "en",
        "data_category": "capital_flows",
        "importance": "medium",
        "content_selectors": ["div.field--name-body", "div.field--type-text-with-summary", "article", "main#content"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    "us_treasury_debt": {
        "strategy": "listing_keywords",
        "url": "https://home.treasury.gov/news/press-releases",
        "base_url": "https://home.treasury.gov",
        "keywords": ["debt", "deficit", "fiscal", "budget"],
        "institution": "Treasury",
        "country": "US",
        "language": "en",
        "data_category": "fiscal_policy",
        "importance": "medium",
        "content_selectors": ["div.field--name-body", "div.field--type-text-with-summary", "article", "main#content"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
    # -- UMich: fixed URL ------------------------------------------------
    "us_umich_sentiment": {
        "strategy": "fixed_url",
        "url": "https://data.sca.isr.umich.edu/",
        "institution": "UMich",
        "country": "US",
        "language": "en",
        "data_category": "consumer_sentiment",
        "importance": "medium",
        "content_selectors": ["article", ".field-item", "#content", ".main-content"],
        "title_selectors": ["h1", "h2", "title"],
        "date_patterns": [
            r"(\w+ \d{1,2},?\s*\d{4})",
            r"(\d{4}-\d{2}-\d{2})",
        ],
    },
}

